# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 06:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceOffering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Service')),
                ('service_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ServiceProvider')),
            ],
        ),
    ]
