# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 08:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_servicerequirement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequirement',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event', to='core.Event'),
        ),
    ]
